name: Composer

on:
    push:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.0, 8.1, 8.2, 8.3]
                laravel: ["8.0", "9.0", "10.0", "11.0"]
                dependency-version: [prefer-lowest, prefer-stable]
                dev-dependencies: [dev, no-dev]

        name: PHP ${{ matrix.php }} - Laravel v${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.dev-dependencies }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install Composer Dependencies
                run: |
                    composer update --${{ matrix.dev-dependencies }} --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -   name: Install Laravel
                run: |
                    composer require "laravel/framework:^${{ matrix.laravel }}" --prefer-dist --no-interaction

