name: 'Pull Request Assignment'

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-assignees:
    name: Add Assignee
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto-assign-assignees.yml'

  add-reviewers:
    name: Add Reviewer
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto-assign-reviewers.yml'